### ISSUE TITLE
[BUG] Manual installation instructions do not include Influxdb installation steps. 

### ISSUE THREAD

**Issue by Zorlin** [AnalogJ/scrutiny#240]
**Describe the bug**
Trying to start the scrutiny-web service on aarch64/arm64 results in a panic: `panic: Post http://0.0.0.0:8086/api/v2/setup: dial tcp 0.0.0.0:8086: connect: connection refused`

This is because InfluxDB is not installed.

**Expected behavior**
Should start successfully.

**Screenshots**

**Log Files**
Full log:
```
blinky:config:% sudo -u scrutiny /opt/scrutiny/bin/scrutiny-web-linux start
2022/05/10 20:23:41 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
github.com/AnalogJ/scrutiny                     linux.arm64-0.4.1

Start the scrutiny server
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

INFO[0000] Trying to connect to scrutiny sqlite db: /opt/scrutiny/config/scrutiny.db
INFO[0000] Successfully connected to scrutiny sqlite db: /opt/scrutiny/config/scrutiny.db
panic: Post http://0.0.0.0:8086/api/v2/setup: dial tcp 0.0.0.0:8086: connect: connection refused

goroutine 1 [running]:
github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.RepositoryMiddleware(0x1191bc0, 0x40000c0cc8, 0x1197780, 0x40003858f0, 0x1191c40)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/repository.go:14 +0xd4
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0x4000382ae0, 0x1197780, 0x40003858f0, 0x14)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:26 +0x90
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0x4000382ae0, 0x0, 0x0)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:97 +0x1f8
main.main.func2(0x4000345e80, 0x4, 0x6)
	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:112 +0x14c
github.com/urfave/cli/v2.(*Command).Run(0x400038b320, 0x4000345d00, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x3ac
github.com/urfave/cli/v2.(*App).RunContext(0x400022ea80, 0x117fb00, 0x40000be010, 0x40000b4020, 0x2, 0x2, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x5bc
github.com/urfave/cli/v2.(*App).Run(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:137 +0x6d0
blinky:config:%
```

**Comment by Zorlin** [comment]
Confirmed that the issue also exists on amd64:
```
wings@scrutiny01:~$ sudo -u scrutiny /opt/scrutiny/bin/scrutiny-web-linux start
2022/05/10 20:58:57 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
github.com/AnalogJ/scrutiny                     linux.amd64-0.4.1

Start the scrutiny server
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

INFO[0000] Trying to connect to scrutiny sqlite db: /opt/scrutiny/config/scrutiny.db
INFO[0000] Successfully connected to scrutiny sqlite db: /opt/scrutiny/config/scrutiny.db
panic: Post http://0.0.0.0:8086/api/v2/setup: dial tcp 0.0.0.0:8086: connect: connection refused

goroutine 1 [running]:
github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.RepositoryMiddleware(0x12ff380, 0xc000010078, 0x1304e80, 0xc0003b6bd0, 0x12ff400)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/repository.go:14 +0xe6
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0xc000067720, 0x1304e80, 0xc0003b6bd0, 0x14)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:26 +0xd8
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0xc000067720, 0x0, 0x0)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:97 +0x234
main.main.func2(0xc00007b380, 0x4, 0x6)
	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:112 +0x198
github.com/urfave/cli/v2.(*Command).Run(0xc0003ab440, 0xc00007b200, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4b9
github.com/urfave/cli/v2.(*App).RunContext(0xc000001500, 0x12ed4c0, 0xc0000be010, 0xc0000b4020, 0x2, 0x2, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x790
github.com/urfave/cli/v2.(*App).Run(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:137 +0x703
```

**Comment by AnalogJ** [comment]
From v0.4.0 onwards, Scrutiny now requires InfluxDB to be installed (which is what it's expecting to communicate with on port `8086`). Apologies, it looks like I forgot to update the [docs/INSTALL_MANUAL.md](https://github.com/AnalogJ/scrutiny/blob/master/docs/INSTALL_MANUAL.md) instructions with those steps.

**Comment by Zorlin** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1369772/167713007-82cfcfd9-41c4-40df-8ad4-36be41c02c94.png">

Confirmed :) Getting the latest InfluxDB installed did the trick.

**Comment by AnalogJ** [comment]
thats great, though I really need to ensure the empty page instructions show up correctly.

**Comment by AnalogJ** [comment]
Added instructions for manual installation. 

https://github.com/AnalogJ/scrutiny/commit/489534cb73f2c4798bc148d86d194a0d96e864d7

Closing, but feel free to reopen if you have any further questions.
