### ISSUE TITLE
[BUG] InfluxDB panic: Unexpected status code 404

### ISSUE THREAD

**Issue by tandy-1000** [AnalogJ/scrutiny#250]
This is a DietPi (debian) RockPro64, I used scrutiny successfully before the new InfluxDB stuff.
I installed InfluxDB and changed the listening ports as I had other services using them.

```
influxd    211702        influxdb    3u  IPv4 44457762      0t0  TCP 127.0.0.1:8888 (LISTEN)
influxd    211702        influxdb   17u  IPv6 44461249      0t0  TCP *:8886 (LISTEN)
```

```
$ cat /opt/scrutiny/config/scrutiny.yaml 
version: 1

web:
  listen:
    port: 9293
    basepath: '/scrutiny'
  database:
    # The Scrutiny webapp will create a database for you, however the parent directory must exist.
    location: /opt/scrutiny/config/scrutiny.db
  src:
    frontend:
      # The path to the Scrutiny frontend files (js, css, images) must be specified.
      # We'll populate it with files in the next section
      path: /opt/scrutiny/web

  influxdb:
    host: localhost
    port: 8886
    retention_policy: true

```

```
$ /opt/scrutiny/bin/scrutiny-web-linux-arm64 start --config /opt/scrutiny/config/scrutiny.yaml
2022/05/14 10:17:51 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
github.com/AnalogJ/scrutiny                     linux.arm64-0.4.4

Start the scrutiny server
2022/05/14 10:17:51 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

INFO[0000] Trying to connect to scrutiny sqlite db: /opt/scrutiny/config/scrutiny.db 
INFO[0000] Successfully connected to scrutiny sqlite db: /opt/scrutiny/config/scrutiny.db 
panic: Unexpected status code 404

goroutine 1 [running]:
github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.RepositoryMiddleware(0x1191580, 0x4000010ce0, 0x1197140, 0x4000378850, 0x1191600)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/repository.go:14 +0xd4
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0x400036b4e0, 0x1197140, 0x4000378850, 0x14)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:26 +0x90
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0x400036b4e0, 0x0, 0x0)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:97 +0x1f8
main.main.func2(0x400031ff80, 0x4, 0x6)
	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:112 +0x14c
github.com/urfave/cli/v2.(*Command).Run(0x40003750e0, 0x400031fe00, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x3ac
github.com/urfave/cli/v2.(*App).RunContext(0x4000376000, 0x117f4c0, 0x4000036090, 0x40000320c0, 0x4, 0x4, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x5bc
github.com/urfave/cli/v2.(*App).Run(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:137 +0x6d0
```

**Comment by AnalogJ** [comment]
Thanks for opening this issue Tandy! It should be easier for me to track context here rather than over chat. 

Couple of quick questions:

- Are you running InfluxDB v2.2 locally?
- What is the output of `curl -vv localhost:8886/health`
- What is the output of `curl -vv localhost:8888/health`

**Comment by tandy-1000** [comment]
Yes, I am running it locally, but it is version 1.6.7~rc0.

```
tandy@server:~$ curl -vv localhost:8886/health
*   Trying 127.0.0.1:8886...
* Connected to localhost (127.0.0.1) port 8886 (#0)
> GET /health HTTP/1.1
> Host: localhost:8886
> User-Agent: curl/7.83.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< X-Influxdb-Build: OSS
< X-Influxdb-Version: 1.6.7~rc0
< Date: Sun, 15 May 2022 09:14:03 GMT
< Content-Length: 19
< 
404 page not found
* Connection #0 to host localhost left intact
```

```
tandy@server:~$ curl -vv localhost:8888/health
*   Trying 127.0.0.1:8888...
* Connected to localhost (127.0.0.1) port 8888 (#0)
> GET /health HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.83.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

**Comment by tandy-1000** [comment]
I just installed InfluxDB 2.2.0 from their repo, and set the new bind port.
But now I get this:

```
$ /opt/scrutiny/bin/scrutiny-web-linux-arm64 start --config /opt/scrutiny/config/scrutiny.yaml
2022/05/15 10:47:32 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
github.com/AnalogJ/scrutiny                     linux.arm64-0.4.4

Start the scrutiny server
2022/05/15 10:47:32 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

INFO[0000] Trying to connect to scrutiny sqlite db: /opt/scrutiny/config/scrutiny.db 
INFO[0000] Successfully connected to scrutiny sqlite db: /opt/scrutiny/config/scrutiny.db 
INFO[0000] Database migration starting                  

2022/05/15 10:47:33 /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/database/scrutiny_repository_migrations.go:62 duplicate column name: label
[0.084ms] [rows:0] ALTER TABLE `devices` ADD `label` text
ERRO[0000] Database migration failed with error: %!w(sqlite3.Error={1 1 0 duplicate column name: label}) 
panic: duplicate column name: label

goroutine 1 [running]:
github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.RepositoryMiddleware(0x1191580, 0x4000010088, 0x1197140, 0x40003d2d20, 0x1191600)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/repository.go:14 +0xd4
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0x40003d8bf0, 0x1197140, 0x40003d2d20, 0x14)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:26 +0x90
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0x40003d8bf0, 0x0, 0x0)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:97 +0x1f8
main.main.func2(0x40000334c0, 0x4, 0x6)
	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:112 +0x14c
github.com/urfave/cli/v2.(*Command).Run(0x40003b57a0, 0x4000033340, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x3ac
github.com/urfave/cli/v2.(*App).RunContext(0x4000001380, 0x117f4c0, 0x40000be010, 0x40000cc000, 0x4, 0x4, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x5bc
github.com/urfave/cli/v2.(*App).Run(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:137 +0x6d0
```

**Comment by tandy-1000** [comment]
Okay, nevermind, I had scrutiny running in the background when testing this, it works now.
I will make a PR to the manual install docs soon with more info.

However, custom basepath does not work, I get a bunch of mime type errors and it never loads.

**Comment by AnalogJ** [comment]
awesome, thanks @tandy-1000 
Can you also open another issue for the custom basepath problem?

**Comment by tandy-1000** [comment]
Will do soon!
