### ISSUE TITLE
[BUG] Manual Install doesn't want to start

### ISSUE THREAD

**Issue by TehloWasTaken** [AnalogJ/scrutiny#254]
**Describe the bug**
Trying to run the standalone manual install of Scrutiny, but running into issues while starting the app. All dependencies are installed but yet the app doesn't start. I saw an issue on here from a couple of days ago with a similar issue (but using docker) so tried an older version, no change there.

**Expected behavior**
Scrutiny to properly run? :P

**Logs:**

```
root@Scrutiny:/opt/scrutiny/bin# /opt/scrutiny/bin/scrutiny-web-linux-amd64 start --config /opt/scrutiny/config/scrutiny.yaml
2022/05/17 11:07:04 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
github.com/AnalogJ/scrutiny                     linux.amd64-0.4.5

Start the scrutiny server
2022/05/17 11:07:04 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

INFO[0000] Trying to connect to scrutiny sqlite db: /opt/scrutiny/config/scrutiny.db 
INFO[0000] Successfully connected to scrutiny sqlite db: /opt/scrutiny/config/scrutiny.db 
panic: Unexpected status code 404

goroutine 1 [running]:
github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.RepositoryMiddleware(0x12ffe60, 0xc000010d08, 0x1305960, 0xc00033e000, 0x12ffee0)
        /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/repository.go:14 +0xe6
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0xc00032d140, 0x1305960, 0xc00033e000, 0x14)
        /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:26 +0xd8
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0xc00032d140, 0x0, 0x0)
        /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:97 +0x234
main.main.func2(0xc0003360c0, 0x4, 0x6)
        /go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:112 +0x198
github.com/urfave/cli/v2.(*Command).Run(0xc000332ea0, 0xc000303f40, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4b9
github.com/urfave/cli/v2.(*App).RunContext(0xc000334000, 0x12edfa0, 0xc000034098, 0xc0000320c0, 0x4, 0x4, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x790
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
        /go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:137 +0x703
       

```

**Comment by AnalogJ** [comment]
Hey @TehloWasTaken 
Yeah I've seen this before. I've fixed this in the current beta, but its not fixed in the master branch yet.

In the meantime, the workaround is to create a scrutiny config file, and make sure the `web.influxdb.host` value is set to `localhost` (not `0.0.0.0`)

```
web:
  influxdb:
    host: localhost
...
```

That should fix your issue, but if you have any other problems, please feel free to reopen this issue.

**Comment by TehloWasTaken** [comment]
Hey @AnalogJ thanks for the swift reply.

The thing is, I am wanting to use an external Influx instance, which I have setup in the config. Why does Scrutiny however require an Influx token to properly work? Can it not be used with Influx 1.8 (the last good update lol)?

**Comment by AnalogJ** [comment]
Scrutiny should work fine with an existing InfluxDB instance, but it does require a InfluxDB token (as the sdk only supports Api auth).

Unfortunately only Influxdb 2+ is supported, the Api and query language has chaffed significantly since v1
