### ISSUE TITLE
[BUG] SMART attributes 0 visible, xx hidden for multiple devices.

### ISSUE THREAD

**Issue by r3mko** [AnalogJ/scrutiny#489]
**Describe the bug**
Drive details page not showing any attributes.

**Expected behavior**
Show all and/or critical attributes.

**Screenshots**
![Screenshot 2023-06-12 at 14 59 47](https://github.com/AnalogJ/scrutiny/assets/11837080/d1718c58-132c-40c6-8f12-747dd621e144)

**Log Files**

Running docker image with v0.7.1

Chrome console error:
`
ERROR TypeError: Cannot read properties of undefined (reading 'attribute_id')
    at i.getAttributeValue (73.b0b3a038183bb5c0.js:1:16885)
    at i._generateSmartAttributeTableDataSource (73.b0b3a038183bb5c0.js:1:18740)
    at Object.next (73.b0b3a038183bb5c0.js:1:16129)
    at ke.next (main.b63012b05e5c3371.js:1:430244)
    at Ue._next (main.b63012b05e5c3371.js:1:429911)
    at Ue.next (main.b63012b05e5c3371.js:1:429594)
    at f._subscribe (main.b63012b05e5c3371.js:1:425270)
    at f._trySubscribe (main.b63012b05e5c3371.js:1:426063)
    at f._trySubscribe (main.b63012b05e5c3371.js:1:428006)
    at main.b63012b05e5c3371.js:1:426005
`

Possibly related to #53 

If you need more information let me know.
Thanks for your help in advance!

**Comment by r3mko** [comment]
**Small update:**

We did replace two disks in the server and now there are two entries for the same "device_type":

`sqlite> select wwn, serial_number, device_type from devices where host_id = 'xxx' and device_type = 'megaraid,55';`
`0x5000cca24dc2bc4e|NCG60K5S|megaraid,55`
`0x5000cca0bec28264|VGG5J3XH|megaraid,55`

`sqlite> select wwn, serial_number, device_type from devices where host_id = 'xxx' and device_type = 'megaraid,63';`
`0x5000cca24dc2e13f|NCG6AD7S|megaraid,63`
`0x5000cca252dbf7c0|7SHZJ8PW|megaraid,63`

I deleted the old ones and still no attributes for the other disks, except for the two new ones.

**Comment by kaysond** [comment]
This issue is being closed automatically as a part of an effort to streamline and prioritize development effort. If it is still relevant, please reply to this comment and we will convert it to a discussion.
