### ISSUE TITLE
Cannot install update

### ISSUE THREAD

**Issue by sezlony** [AnalogJ/scrutiny#605]
**Describe the bug**
Installin update from 0.7.3 to 0.8.0 simply crashes

**Expected behavior**
clean install

**Screenshots**
n/a

**Log Files**
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:240
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8:19:10 PM (5 occurrences)
Last logged: 8:21:43 PM

[139905120808384] Error updating Scrutiny (Full Access): Can't install ghcr.io/alexbelgium/scrutiny-fa-amd64:v0.8.0: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=v0.8.0&fromImage=ghcr.io%2Falexbelgium%2Fscrutiny-fa-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 55, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install ghcr.io/alexbelgium/scrutiny-fa-amd64:v0.8.0: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=v0.8.0&fromImage=ghcr.io%2Falexbelgium%2Fscrutiny-fa-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 161, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 465, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Scrutiny (Full Access): Can't install ghcr.io/alexbelgium/scrutiny-fa-amd64:v0.8.0: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=v0.8.0&fromImage=ghcr.io%2Falexbelgium%2Fscrutiny-fa-amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")
```

**Comment by martadinata666** [comment]
upgrade docker version

**Comment by sezlony** [comment]
@martadinata666: using HASSOS that wouldn't make any sense

**Comment by martadinata666** [comment]
For what ever way homeassistant pull image or deploy, it cant find manifest. That only mean the  image doesn't exist or the docker too old to read new manifest. Ask the homeassistant add-ons to get more info https://github.com/alexbelgium/hassio-addons

**Comment by sezlony** [comment]
@martadinata666: seems like it's now solved by developer (https://github.com/alexbelgium/hassio-addons/issues/1305)

**Comment by alexbelgium** [comment]
Indeed for addon related questions please post on my repo and I would redirect here only after making sure that everything is fine on addon side. For example here I had to adapt for the switch of /bin/sh to /usr/bin/sh which is entirely on addon side. Have a nice day all!
