### ISSUE TITLE
Anwendung startet nicht - Webseite nicht erreichbar

### ISSUE THREAD

**Issue by varo-biker** [AnalogJ/scrutiny#669]
**Describe the bug**

Hello,

I installed the Docker container (see below) via the console. 
The following log (see log files) can be seen in the Portainer.
Unfortunately I cannot access the server via http://<ip host:8080>. The website always cannot be accessed.

Where is the/my mistake?
-----------------------------------------------------------------------------------------------------------------------------------------------
**Screenshots**
-----------------------------------------------------------------------------------------------------------------------------------------------
**Log Files**
 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
github.com/AnalogJ/scrutiny                            dev-0.4.13
Start the scrutiny server
time="2024-07-30T09:28:47+02:00" level=info msg="Trying to connect to scrutiny sqlite db: \n"
time="2024-07-30T09:28:47+02:00" level=info msg="Successfully connected to scrutiny sqlite db: \n"
panic: failed to check influxdb setup status - parse "://:": missing protocol scheme
goroutine 1 [running]:
github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.RepositoryMiddleware({0xfe6620, 0x4000010088}, {0xfef580, 0x40004585b0})
	/app/scrutiny/webapp/backend/pkg/web/middleware/repository.go:14 +0xd4
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0x4000063250, {0xfef580, 0x40004585b0})
	/app/scrutiny/webapp/backend/pkg/web/server.go:27 +0x90
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0x4000063250)
	/app/scrutiny/webapp/backend/pkg/web/server.go:105 +0x530
main.main.func2(0x4000401280)
	/app/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:112 +0x288
github.com/urfave/cli/v2.(*Command).Run(0x400045e480, 0x4000401100)
	/app/scrutiny/vendor/github.com/urfave/cli/v2/command.go:164 +0x648
github.com/urfave/cli/v2.(*App).RunContext(0x4000464000, {0xfd28d0, 0x40000b8000}, {0x40000b6000, 0x2, 0x2})
	/app/scrutiny/vendor/github.com/urfave/cli/v2/app.go:306 +0x840
github.com/urfave/cli/v2.(*App).Run(...)
	/app/scrutiny/vendor/github.com/urfave/cli/v2/app.go:215
main.main()
	/app/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:137 +0x73c

-----------------------------------------------------------------------------------------------------------------------------------------------
```
docker run -d \
  --name=scrutiny \
  --cap-add=SYS_RAWIO \
  --cap-add=SYS_ADMIN `#optional` \
  -e PUID=1003 \
  -e PGID=1003 \
  -e TZ=Europe/Berlin \
  -e SCRUTINY_API_ENDPOINT=http://localhost:8080 \
  -e SCRUTINY_WEB=true \
  -e SCRUTINY_COLLECTOR=true \
  -p 8080:8080 \
  -v /var/lib/docker/scrutiny:/config \
  -v /run/udev:/run/udev:ro \
  --device /dev/nvme0n1:/dev/nvme0n1 \
  --restart unless-stopped \
  lscr.io/linuxserver/scrutiny:latest
-------------------------------------------------------------------------------------------------------------------------------------------
# in another terminal trigger the collector
docker exec scrutiny scrutiny-collector-metrics run

2024/07/30 09:35:23 No configuration file found at /opt/scrutiny/config/collector.yaml. Using Defaults.

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
AnalogJ/scrutiny/metrics                               dev-0.4.13

time="2024-07-30T09:35:23+02:00" level=info msg="Verifying required tools" type=metrics
time="2024-07-30T09:35:23+02:00" level=info msg="Executing command: smartctl --scan --json" type=metrics
time="2024-07-30T09:35:24+02:00" level=info msg="Sending detected devices to API, for filtering & validation" type=metrics
2024/07/30 09:35:24 ERROR: Post "http://localhost:8080/api/devices/register": dial tcp 127.0.0.1:8080: connect: connection refused```
-----------------------------------------------------------------------------------------------------------------------------------------------
The log files will be available on your host in the `config` directory. Please attach them to this issue. 
-----------------------------------------------------------------------------------------------------------------------------------------------
Please also provide the output of `docker info`
Client:
 Version:    24.0.7
 Context:    default
 Debug Mode: false

Server:
 Containers: 24
  Running: 24
  Paused: 0
  Stopped: 0
 Images: 27
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-1008-raspi
 Operating System: Ubuntu 24.04 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.756GiB
 Name: Cocker-SRV-5
 ID: de5db041-e599-457c-a96b-0d5703a29f91
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by kapsh** [comment]
LinuxServer deprecated this image 2 years ago and recommends using official images. But if you still need it for some reason, add `SCRUTINY_WEB=true` variable.

**Comment by AnalogJ** [comment]
closing, this is related to the LSIO images.
